service: ServiceON-DL-SLOT
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ca-central-1
  memorySize: 512
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"
plugins:
  - serverless-offline
functions:
  getSlots:
    handler: functions/dl/dl.getSlots
    description: "check for availabel slots every few minutes and send email"
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: true
      
  